# DSC200 Lecture 7

## An introduction to NumPy (cont.)

## Recap

In [27]:
import numpy as np

In [28]:
arr = np.array([10, 20, 30, 40])
arr[1:-1]

array([20, 30])

In [29]:
np.ones(5) * 5.

array([5., 5., 5., 5., 5.])

Arrays also have many useful statistical/mathematical methods:

In [30]:
print('Minimum and maximum             :', arr.min(), arr.max())
print('Sum and product of all elements :', arr.sum(), arr.prod())
print('Mean and standard deviation     :', arr.mean(), arr.std())

Minimum and maximum             : 10 40
Sum and product of all elements : 100 240000
Mean and standard deviation     : 25.0 11.180339887498949


## Arrays with more than one dimension

A list of lists can be used to initialize a two dimensional array:

In [31]:
lst2 = [[1, 2, 3], [4, 5, 6]]
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [32]:
print(lst2[0][1])
print(arr2[0, 1])

2
2


Question: Why does the following example produce different results?

In [33]:
print(lst2[0:2][1])
print(arr2[:, 1])

[4, 5, 6]
[2 5]


### Multidimensional array creation

The array creation functions listed previously can also be used to create arrays with more than one dimension.

For example:

In [34]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.random.normal(10, 3, size=(2, 4))

array([[11.92938935,  7.06676968,  6.2187999 ,  9.40952037],
       [ 6.9248658 ,  6.72218742, 10.71764905,  8.50533261]])

In fact, the shape of an array can be changed at any time, as long as the total number of elements is unchanged.

For example, if we want a 2x4 array with numbers increasing from 0, the easiest way to create it is:

In [36]:
arr = np.arange(8).reshape(-1, 4)
print(arr)

[[0 1 2 3]
 [4 5 6 7]]


### Slices

With multidimensional arrays you can also index using slices, and you can mix and match slices and single indices in the different dimensions:

In [37]:
arr = np.arange(2, 18, 2).reshape(2, 4)
print(arr)

[[ 2  4  6  8]
 [10 12 14 16]]


In [38]:
print('Second element from dimension 0, last 2 elements from dimension one:')
print(arr[1, 2:])

Second element from dimension 0, last 2 elements from dimension one:
[14 16]


If you only provide one index to slice a multidimensional array, then the slice will be expanded to ``":"`` for all of the remaining dimensions:

In [39]:
print('First row:  ', arr[0], 'is equivalent to', arr[0, :])
print('Second row: ', arr[1], 'is equivalent to', arr[1, :])

First row:   [2 4 6 8] is equivalent to [2 4 6 8]
Second row:  [10 12 14 16] is equivalent to [10 12 14 16]


This is also known as "ellipsis".

Ellipsis can be specified explicitly with ```"..."```. It will automatically expand to `":"` for each of the unspecified dimensions in the array, and can even be used at the beginning of the slice:

In [40]:
arr1 = np.empty((4, 6, 3))
print('Orig shape: ', arr1.shape)
print(arr1[...].shape)
print(arr1[..., 0:2].shape)
print(arr1[2:4, ..., ::2].shape)
print(arr1[2:4, :, ..., ::-1].shape)

Orig shape:  (4, 6, 3)
(4, 6, 3)
(4, 6, 2)
(2, 6, 2)
(2, 6, 3)


What is the shape of this slice:

In [41]:
arr3 = np.empty((5, 6, 7, 8))
print('Orig shape: ', arr3.shape)
print(arr3[2:3, ..., :4].shape)

Orig shape:  (5, 6, 7, 8)
(1, 6, 7, 4)


<table border="1" class="docutils">
<colgroup>
<col width="14%" />
<col width="86%" />
</colgroup>
<thead valign="bottom">
<tr class="row-odd"><th class="head"></th>
<th class="head">Shape</th>
</tr>
</thead>
<tbody valign="top">
<tr class="row-even"><td><tt class="docutils literal"><span class="pre">A</span></tt></td>
<td>(3, 6, 7, 4)</td>
</tr>
<tr class="row-odd"><td><tt class="docutils literal"><span class="pre">B</span></tt></td>
<td>(1, 6, 7, 4)</td>
</tr>
<tr class="row-even"><td><tt class="docutils literal"><span class="pre">C</span></tt></td>
<td>(6, 7, 5)</td>
</tr>
<tr class="row-odd"><td><tt class="docutils literal"><span class="pre">D</span></tt></td>
<td>(6, 7, 4)</td>
</tr>
</tbody>
</table>

## Operating with arrays

Arrays support all regular arithmetic operators, and the NumPy library also contains a complete collection of basic mathematical functions that operate on arrays.  

It is important to remember that in general, all operations with arrays are applied *element-wise*, i.e., are applied to all the elements of the array at the same time.  For example:

In [42]:
arr1 = np.arange(4)
arr2 = np.arange(10, 14)
print(arr1, '+', arr2, '=', arr1 + arr2)

[0 1 2 3] + [10 11 12 13] = [10 12 14 16]


Importantly, even the multiplication operator is by default applied element-wise: It is *not* the matrix multiplication from linear algebra:

In [43]:
print(arr1, '*', arr2, '=', arr1 * arr2)

[0 1 2 3] * [10 11 12 13] = [ 0 11 24 39]


We may also multiply an array by a scalar:

In [44]:
arr1 * 1.5

array([0. , 1.5, 3. , 4.5])

This is an example of **broadcasting**.

### Broadcasting

The fact that NumPy operates on an element-wise basis means that in principle arrays must always match one another's shape. However, NumPy will also helpfully "*broadcast*" dimensions when possible.  

Here is an example of broadcasting a scalar to a 1D array:

In [45]:
print(np.arange(3))
print(np.arange(3) + 5)

[0 1 2]
[5 6 7]


We can also broadcast a 1D array to a 2D array, in this case adding a vector to all rows of a matrix:

In [46]:
np.ones((3, 3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

We can also broadcast in two directions at a time:

In [47]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)
print(a, '+', b, '=\n', a + b)

[[0]
 [1]
 [2]] + [0 1 2] =
 [[0 1 2]
 [1 2 3]
 [2 3 4]]


### Rules of Broadcasting

Broadcasting follows these three rules:

1. If the two arrays differ in their number of dimensions, the shape of the array with fewer dimensions is *padded* with ones on its leading (left) side.

2. If the shape of the two arrays does not match in any dimension, either array with shape equal to 1 in a given dimension is *stretched* to match the other shape.

3. If in any dimension the sizes disagree and neither has shape equal to 1, an error is raised.

Note that all of this happens without ever actually creating the expanded arrays in memory! This broadcasting behavior is in practice enormously powerful, especially given that when NumPy broadcasts to create new dimensions or to 'stretch' existing ones, it doesn't actually duplicate the data.  In the example above the operation is carried out *as if* the scalar 1.5 was a 1D array with 1.5 in all of its entries, but no actual array is ever created.  This can save lots of memory in cases when the arrays in question are large. As such this can have significant performance implications.

Pictorially:

![Illustration of broadcasting](https://github.com/climate-analytics-lab/dsc200-fa25-public/blob/main/lectures/images/fig_broadcast_visual_1.png?raw=1)

([image source](http://www.astroml.org/book_figures/appendix/fig_broadcast_visual.html))

### Broadcasting Examples

So when we do...

    np.arange(3) + 5
    
The scalar 5 is:

* first 'promoted' to a 1-dimensional array of length 1 (rule 1)
* then, this array is 'stretched' to length 3 to match the first array. (rule 2)

After these two operations are complete, the addition can proceed as now both operands are one-dimensional arrays of length 3.

When we do

    np.ones((3, 3)) + np.arange(3)
    
The second array is:

- first 'promoted' to a 2-dimensional array of shape (1, 3) (rule 1)
- then axis 0 is 'stretched' to length 3 to match the first array (rule 2)

When we do

    np.arange(3).reshape((3, 1)) + np.arange(3)
    
The second array is:

- first 'promoted' to a 2-dimensional array of shape (1, 3) (rule 1)
- then axis 0 is 'stretched' to form an array of shape (3, 3) (rule 2)
- and the first array's axis 1 is 'stretched' to form an array of shape (3, 3) (rule 2)

Then the operation proceeds as if on two 3 $\times$ 3 arrays.

The general rule is: when operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward, creating dimensions of length 1 as needed. Two dimensions are considered compatible when

* they are equal to begin with, or
* one of them is 1; in this case NumPy will do the 'stretching' to make them equal.

If these conditions are not met, a `ValueError: operands could not be broadcast together` exception is thrown, indicating that the arrays have incompatible shapes.

### Questions:

What will the result of adding ``arr1`` with ``arr2`` be in the following cases?

In [48]:
arr1 = np.ones((2, 3))
arr2 = np.ones((2, 1))

arr1 + arr2

array([[2., 2., 2.],
       [2., 2., 2.]])

In [49]:
arr1 = np.ones((2, 3))
arr2 = np.ones(3)

(arr1 + arr2).shape

(2, 3)

In [50]:
arr1 = np.ones((1, 3))
arr2 = np.ones((2, 1))

arr1 + arr2

array([[2., 2., 2.],
       [2., 2., 2.]])

In [51]:
arr1 = np.ones((1, 3))
arr2 = np.ones((1, 2))

# arr1 + arr2

In [52]:
arr1 = np.ones((1, 3))
arr3 = np.ones((1, 2))[:, :, np.newaxis]

(arr1 + arr3).shape

(1, 2, 3)